apiVersion: v1
kind: Secret
metadata:
  name: rp-secrets
  namespace: rp-prod
type: Opaque
stringData:
  DATABASE_URL: "${DATABASE_URL}"
  BETTER_AUTH_SECRET: "${BETTER_AUTH_SECRET}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
  MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
